### ISSUE TITLE
Disque doesn't seem to reclaim memory.

### ISSUE THREAD

**Issue by jlouis** [antirez/disque#22] opened 2015-04-28 19:35 UTC
Hi,

This may be a misunderstanding about the inner working of disque, but I have run into an issue where disque reports the following to me:

```
NOREPL Not enough reachable nodes for the requested replication level, since I'm unable to hold a copy of the message for memory usage problems.
```

This happens if we execute the following series of commands around 200k times, on a single disque server, no clustering:
1. GETJOB all jobs on a queue `test_queue`.
2. ACKJOB on all the jobs we just got.
3. Call QLEN on `test_queue` - see that there are 0 jobs.
4. Add the following jobs `ADDJOB test_queue X 300` with the following jobs (the notation `<<>>` denotes the empty string, wheras `<<X,Y,Z,...>>` means the decimal representation of bytes X,Y,Z,...:

```
<<>>
<<209,100,0,105,182,14,6,2,62>>
<<39,157,129,26,95,242,121>>
<<232,223,179,218,130,58>>
<<>>
<<237,158,171,168,97>>
<<63,126>>
<<61,96,195,99,167,139>>
```
1. Go back to 1, next round.

After around 200k runs of this (that is 200k \* 8 addjob commands, with a "reset" in between as in 1-3 above), we eventually reach a disque-server process (with standard configuration), using up 800 megabytes of memory. Once this happens, it starts reporting the above message.

It would seem plausible that some of the jobs, perhaps all of them, are not ACK'ed and removed properly, because the server should clean up before sending the above NOREPL notion in which it states that it is practically out of memory.

**Comment by antirez** [comment] 2015-04-29 06:46
When it starts to complain, what happens is that it reached 75% of used memory and is trying to externally replicate the job to another node, but there are none available. However as you say, if you acknowledge all the jobs you add, this should definitely not be the case since we expect that all the memory is reclaimed: acknowledging a job that is only replicated in the local node should be a synchronous operation resulting in immediate cleanup. So there is something wrong going on apparently. I'll try to replicate the issue. Thanks for reporting.

**Comment by antirez** [comment] 2015-04-29 07:31
I tried to replicate this problem without success using the following script:

```
require 'rubygems'
require 'redis'

r = Redis.new(:port => 9999)
100000.times {
    10.times {
        r.addjob("queue","myjob","300")
    }
    puts r.qlen("queue");
    jobs = r.getjob("count","100","from","queue")
    jobs.each{|j|
        r.ackjob(j[1])
    }
}
```

Is it possible that for some reason some job is not acknowledged by your script, or otherwise, that jobs already acknowledged gets re-acknowledged creating a dummy ack?

One way to inspect this issue could be the `MONITOR` command which works the same as in Redis. Taking the issue open in order to investigate. Otherwise you may want to share your script to reproduce the issue, maybe I'm doing things in a way that don't trigger the bug. Thanks.

**Comment by antirez** [comment] 2015-04-29 07:43
p.s. note that in my script I assumed the job content does not change anything, as it's just a string, but if we can't find other clues I can try with the same bytes you used. However it would be very surprising the content of the job which is just a variable string may change the behavior of the acknowledge.

You may quickly confirm this by using a fixed string in your test as well, we should see the issue anyway.

**Comment by jlouis** [comment] 2015-04-29 11:06
I'll take a deeper look at what happens in my end, since it is likely there is something I don't understand about the way `disque` is supposed to work. How do you safely wipe a queue for instance? The above method, using QLEN is obviously wrong since it won't report the jobs which has already been given out via GETJOB calls. In RabbitMQ-speak QLEN reports the messages which are "ready" for consumption, not the ones which are "unacknowledged" because they were given out to connections for processing and are awaiting the return of an ACKJOB.

The code I'm using is online at https://github.com/jlouis/disque_eqc/blob/master/src/disque_eqc.erl but it is not that easy to get to run (part of the code requires a commercial license, unfortunately). Essentially what I'm doing is to define a property, in the sense of property-based-testing, which generates a random command sequence and then executes it against disque through a single sequential connection. I've been running around a million different tests with an average length of 12 commands or so. In other words, some 12 million commands. It has not turned up anything, apart from my above "leak"--which may not be a leak after all. I think there is a bug in around the cleanup-phase, as I surmise above.

This may also explain #23, which I haven't seen for a long time in the tests.

**Comment by jlouis** [comment] 2015-04-29 11:13
It is definitely not a `disque` bug this one. It is a model bug in my model. It can be closed, apart from the notion of a way to delete a queue safely (but as you say in #14 what does that really entail?)

**Comment by jlouis** [comment] 2015-04-29 11:21
Fixed in https://github.com/jlouis/disque_eqc/commit/2b5638d4c94c57a280addcc183772b482e0e635c and now there are no leak in sight.

**Comment by antirez** [comment] 2015-04-29 14:01
Thank you, closing the issue.

**Closed as completed by antirez** 2015-04-29 14:01 UTC
